# Generated by Django 4.2.7 on 2026-09-23 02:12

from django.db import migrations, models
import djmoney.models.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UAH', max_digits=10, verbose_name='Общая стоимость')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UAH', max_digits=10, verbose_name='Общая стоимость')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Бронирование',
                'verbose_name_plural': 'historical Бронирования',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
