# Generated by Django 4.2.7 on 2026-09-23 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listing', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['-created_at'], name='search_quer_created_824a49_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', '-created_at'], name='search_quer_user_id_486cee_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', '-created_at'], name='listing_vie_listing_f85de9_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', '-created_at'], name='listing_vie_user_id_7382ce_idx'),
        ),
    ]
